#!/bin/bash
read -p "Are you sure you want to erase your janusgraph database, index, logs as well as elasticsearch and scylla backends? " -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
    # Created as root can not remove uness want to run script or this command as root 
    # rm -rf ./details/log
    docker volume rm details_jgvolume
    docker volume rm details_elsvolume
    docker volume rm details_scyvolume
fi
echo OK, its erased
