#!/bin/bash
echo Stopping Janusgraph.... to restart, use ./janus-up
docker-compose -f ./details/janus.yaml down
echo Stopped...  your data is saved in various docker managed volumes.  To erase it, use ./janus-erase
