#!/bin/bash
read -p "Are you sure you want to erase your tinkertools script database? " -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
    rm -rf ./details/data/mongodb
fi
echo OK, its erased

