hosts: [localhost]
port: 8182
username: catapult4Catapult
password: password
serializer: { className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV3d0, config: { serializeResultToString: true }}
